[package]
name = "game2048"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.9.2", default-features = false, features = ["small_rng"] }
ultraviolet = "0.10.0"
thiserror = "2.0.17"

[build-dependencies]
crossterm = "0.26"
